//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPublic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleSection
    {
        public int id_article { get; set; }
        public int id_section { get; set; }
        public int priority { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Section Section { get; set; }
    }
}
