//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPublic
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormItem()
        {
            this.FormItemFields = new HashSet<FormItemField>();
        }
    
        public int id_item { get; set; }
        public int id_user { get; set; }
        public int id_form { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime editdate { get; set; }
        public int version { get; set; }
        public bool saved { get; set; }
        public int id_group { get; set; }
        public bool released { get; set; }
        public int id_item_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormItemField> FormItemFields { get; set; }
    }
}
