//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPublic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.ArticleSections = new HashSet<ArticleSection>();
        }
    
        public int id_section { get; set; }
        public int id_metasection { get; set; }
        public int id_server { get; set; }
        public int id_section_parent { get; set; }
        public int id_section_parent_top { get; set; }
        public byte treelevel { get; set; }
        public string name { get; set; }
        public string redirurl { get; set; }
        public byte target { get; set; }
        public bool visible { get; set; }
        public bool del { get; set; }
        public int order { get; set; }
        public int options { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleSection> ArticleSections { get; set; }
    }
}
