//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetPublic
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffItem
    {
        public int id_item { get; set; }
        public string ODBOR { get; set; }
        public string JMENO { get; set; }
        public string KRESTNI { get; set; }
        public string PRIJMENI { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public string MISTNOST { get; set; }
        public string WWW { get; set; }
        public string FUNKCE1 { get; set; }
        public string FUNKCE2 { get; set; }
        public string FUNKCE1_ENG { get; set; }
        public string FUNKCE2_ENG { get; set; }
        public int FOTO { get; set; }
        public string SHOW_HEADER { get; set; }
        public string SHOW_FOTO { get; set; }
        public string STYL { get; set; }
        public string INFO { get; set; }
        public string EMAIL1 { get; set; }
        public string ID_OSOBY { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
