//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleSections = new HashSet<ArticleSection>();
            this.Chapters = new HashSet<Chapter>();
            this.Users = new HashSet<User>();
        }
    
        public int id_article { get; set; }
        public int id_metaarticle { get; set; }
        public int id_server { get; set; }
        public int id_arttype { get; set; }
        public int id_user { get; set; }
        public string title { get; set; }
        public string annotation { get; set; }
        public string imageurl { get; set; }
        public string redirurl { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime edited { get; set; }
        public bool released { get; set; }
        public System.DateTime datereleased { get; set; }
        public System.DateTime datestop { get; set; }
        public short chaptercount { get; set; }
        public string keywords { get; set; }
        public bool forum { get; set; }
        public int forumitems { get; set; }
        public System.DateTime forumlastitem { get; set; }
        public bool complete { get; set; }
        public bool del { get; set; }
        public byte[] tmstamp { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleSection> ArticleSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapter> Chapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
