//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int id_item { get; set; }
        public string semester { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string name_eng { get; set; }
        public string name_code { get; set; }
        public Nullable<int> id_file { get; set; }
        public Nullable<int> engprog { get; set; }
        public string cvis_id { get; set; }
    }
}
