//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int id_item { get; set; }
        public Nullable<int> id_user { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int id_file { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string course_code { get; set; }
    
        public virtual File File { get; set; }
    }
}
