//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Files = new HashSet<File>();
            this.Folders = new HashSet<Folder>();
            this.Articles = new HashSet<Article>();
            this.Articles1 = new HashSet<Article>();
        }
    
        public int id_user { get; set; }
        public string login_name { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string full_name { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string ico { get; set; }
        public string dic { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mobil { get; set; }
        public string url { get; set; }
        public byte dealergroup { get; set; }
        public decimal discount { get; set; }
        public int type { get; set; }
        public byte logcount { get; set; }
        public string controlq { get; set; }
        public string controla { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public int options { get; set; }
        public bool author { get; set; }
        public bool enabled { get; set; }
        public bool locked { get; set; }
        public bool del { get; set; }
        public System.DateTime password_chng_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Folder> Folders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles1 { get; set; }
    }
}
