//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPage
    {
        public int id_userpage { get; set; }
        public int id_user { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string body { get; set; }
        public int order { get; set; }
        public bool show { get; set; }
    }
}
